#!/bin/sh

# start albert daemon
if command -v albert >/dev/null; then
  albert &
fi

# load xrandr layout config
if [ -f ~/.screenlayout/default-layout.sh ]; then
  ~/.screenlayout/default-layout.sh
fi

# start ssh-agent
if command -v ssh-agent >/dev/null; then
  eval "$(ssh-agent -s)"
fi

# set keyboard repeat delay & rate
xset r rate 450 45

# lock on inactivity
xautolock -time 10 -locker ~/.local/bin/i3lock-with-blur -secure &
