#!/bin/sh

if command -v pacman > /dev/null; then
  echo "----> Install the following packages"

  echo
  echo pacman -Sy --needed --noconfirm \
    bash-completion git kitty ncurses neovim pyenv python2 tmux \
    xmonad xmonad-contrib xmobar
  echo
fi

if command -v auracle > /dev/null; then
  echo "----> Download and install the following aur packages"

  echo
  echo auracle clone \
    albert \
    arc-icon-theme-git \
    direnv \
    haskell-ide-engine \
    i3lock-blur \
    joker-bin \
    kubernetes-bin \
    leiningen \
    muparser \
    mysql-connector-java \
    nvm \
    rbenv \
    ruby-build \
    stern-bin
  echo

  echo "----> Download Sway and deps"

  echo
  echo pacman --needed -S \
       grim \
       i3status \
       kitty \
       mako \
       sway \
       swaybg \
       swayidle \
       swaylock \
       wallutils \
       waybar \
       xorg-server-xwayland
  echo
fi
